### ISSUE TITLE
CRUD commands for customers & orders should bring the target to focus on information panel

### ISSUE THREAD

**Issue by Junyi00** [AY2223S2-CS2103T-T09-3/tp#66]
## Current situation
Adding, editing and deleting commands of `Customer` and `Order` currently does nothing on top of its operation.

## Desired Behaviour
These commands should bring the target directly to view on information panel so that the user does not have to search for it to verify that the command succeeded. Furthermore, the tab pane for customer and order should be automatically selected based on whether its a customer or order command.

eg. `addo`, the added order should appear on the informational panel if the command succeeds. Furthermore, the order tab is activated and selects the row of the new order.

**Comment by CloudHill** [comment]
This can be considered a functionality bug, as this behavior is already specified in the use cases in the developer guide in the beginning, yet is not being reflected.
